server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/udemy}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

auth:
  jwt:
    base64-secret-access: ${JWT_SECRET_ACCESS}
    base64-secret-fresh: ${JWT_SECRET_REFRESH}
    access-token-validity-in-seconds: 8640000
    refresh-token-validity-in-seconds: 8640000

upload:
  file:
    uri: ${UPLOAD_URI:file:///E:/Udemy/upload/}
    image-uri: ${UPLOAD_IMAGE_URI:file:///E:/Udemy/upload/images/}
    video-uri: ${UPLOAD_VIDEO_URI:file:///E:/Udemy/upload/videos/}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

resend:
  api-key: ${RESEND_API_KEY}
  from-email: onboarding@resend.dev

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
  facebook:
    app-id: ${FACEBOOK_APP_ID}
vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  url: ${VNPAY_URL}
  return-url: ${VNPAY_RETURN_URL}
  frontend-url: http://localhost:8081
gemini:
  api-key: ${GEMINI_API_KEY}